version: "2"
services:
  tf2:
    image: team-brh/tf2:latest
    dns: 
      - 172.28.0.2
    networks: 
      - game-network
    depends_on: 
      - dns
      - cache
  
  css:
    image: team-brh/css:latest
    dns: 
      - 172.28.0.2
    networks: 
      - game-network
    depends_on: 
      - dns
      - cache

  pz:
    image: team-brh/pz:latest
    dns: 
      - 172.28.0.2
    networks: 
      - game-network
    depends_on: 
      - dns
      - cache
    volumes:
      - pz_db:/home/steam/Zomboid/db
      - pz_save:/home/steam/Zomboid/Saves

  cache:
    image: steamcache/monolithic
    volumes:
      - cache:/data/cache/
    networks: 
      game-network:
        ipv4_address: 172.28.0.1
    depends_on: 
      - dns
        
  dns:
    image: steamcache/steamcache-dns
    environment:
      - USE_GENERIC_CACHE=true 
      - LANCACHE_IP=172.28.0.1
    networks: 
      game-network:
        ipv4_address: 172.28.0.2

  fastdownload:
    image: nginx:1
    ports:
      - "69.162.82.212:38929:80"
    volumes:
      - ./containers/fastdownload/default.conf:/etc/nginx/conf.d/default.conf:ro
      - fast_download:/fastdownload:ro

volumes: 
  cache:
  pz_db:
  pz_save:
  fast_download:

networks:
  game-network:
    ipam:
      config:
      - subnet: 172.28.0.0/16
        ip_range: 172.28.5.0/24